### ISSUE TITLE
Hot module reloading not reflecting changes on browser

### ISSUE THREAD

**Issue by aseem2625** [lukeed/inferno-starter#5]
For any changes in ```css/jsx``` code, HMR does recompile, however , the browser doesn't reflect the changes if done on JSX. (CSS works fine)

Can you please confirm?
Thanks

**Comment by aseem2625** [comment]
Updated to latest inferno and inferno-router ```3.1.0```. Works now. However, **it's not hot reloading. It's live reloading!**

**Comment by lukeed** [comment]
Hmm.. 🤔 I'll look into this today!

**Comment by lukeed** [comment]
So live-reloading the JS files is the best Inferno can do right now. I remember this from discussions from a few months ago. However, I might not be up to date. But after toying with it for 20m, I arrived at the same conclusion.

This is because [`Inferno.render`](https://github.com/infernojs/inferno#render-package-inferno) clears _everything_ within the "container" node. And I'm pretty sure the actual `location.reload` is coming from re-instantiating `createBrowserHistory()`.

Sorry for the bad news, but live-reloading is still really quick!
